### PR TITLE
feature/freebsd-support-one: add include and endian.h

### PR DESCRIPTION
**Pull request by cosmicpsyop**
while preferring the use of gnu as in gmake and g++ the posix c++ and make works as well in this case.  there is some Makefile fukery in that the obvious place to put the include addition did not work.
INCS     = -Isrc/ -I/usr/local/include

### CODE REVIEW

**Comment by hoytech** [comment]
Thank you!!

**Comment by hoytech** [comment]
I'm not sure why it isn't working in `INCS`. Just to be clear: The redundant include is only needed with `make` (not `gmake`) right? If so, maybe we can just mandate `gmake`. There are probably other gmake-specific features I'm using elsewhere.

**Comment by cosmicpsyop** [comment]
removed the redundant. not sure either.  the intent of the change below was to override standard flags that ensure gnu over posix is used in child makefiles.
https://github.com/hoytech/golpe/pull/1/files#diff-d19cc9f90074647454f3939920d2e52b99a9a2c4dbc98d2789092eda7c55b75fR11

**Comment by hoytech** [comment]
Thank you!

**Pull request merged**
